from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]

INPUT_DIR = ROOT_DIR / "input"
OUTPUT_DIR = ROOT_DIR / "output"
CACHE_DIR = ROOT_DIR / "cache"
ASSETS_DIR = ROOT_DIR / "assets"
DATA_DIR = ROOT_DIR / "data"

OUTPUT_LONG_DIR = OUTPUT_DIR / "long"
OUTPUT_SHORTS_DIR = OUTPUT_DIR / "shorts"
OUTPUT_VERTICAL_DIR = OUTPUT_DIR / "vertical"
OUTPUT_SUBTITLES_DIR = OUTPUT_DIR / "subtitles"
OUTPUT_THUMBNAILS_DIR = OUTPUT_DIR / "thumbnails"

CACHE_AUDIO_DIR = CACHE_DIR / "audio"
CACHE_AUDIO_CHUNKS_DIR = CACHE_AUDIO_DIR / "chunks"
CACHE_METADATA_DIR = CACHE_DIR / "metadata"
CACHE_TRANSCRIPTS_DIR = CACHE_DIR / "transcripts"
CACHE_TRANSCRIPTION_CHUNKS_DIR = CACHE_TRANSCRIPTS_DIR / "chunks"
CACHE_HIGHLIGHTS_DIR = CACHE_DIR / "highlights"
CACHE_EDIT_PLANS_DIR = CACHE_DIR / "edit_plans"
CACHE_VIDEO_DIR = CACHE_DIR / "video"
CACHE_CONTEXT_DIR = CACHE_DIR / "context"
CACHE_EMOTIONS_DIR = CACHE_DIR / "emotions"
CACHE_TITLES_DIR = CACHE_DIR / "titles"
CACHE_PUBLISH_DIR = CACHE_DIR / "publishing"
CACHE_LEARNING_DIR = CACHE_DIR / "learning"
CACHE_ANALYTICS_DIR = CACHE_DIR / "analytics"

DATA_ANALYTICS_DIR = DATA_DIR / "analytics"

ASSETS_SFX_DIR = ASSETS_DIR / "sfx"
ASSETS_FONTS_DIR = ASSETS_DIR / "fonts"
ASSETS_OVERLAYS_DIR = ASSETS_DIR / "overlays"

DEFAULT_INPUT_VIDEO_PATH = INPUT_DIR / "live_bruta.mp4"

DEFAULT_AUDIO_PATH = CACHE_AUDIO_DIR / "audio.wav"
DEFAULT_TRANSCRIPT_PATH = CACHE_TRANSCRIPTS_DIR / "transcript.json"
DEFAULT_SUBTITLES_SRT_PATH = CACHE_TRANSCRIPTS_DIR / "subtitles.srt"
DEFAULT_SUBTITLES_ASS_PATH = CACHE_TRANSCRIPTS_DIR / "subtitles.ass"
DEFAULT_HIGHLIGHTS_PATH = CACHE_HIGHLIGHTS_DIR / "highlights.json"
DEFAULT_EDIT_PLAN_PATH = CACHE_EDIT_PLANS_DIR / "edit_plan.json"

PROJECT_DIRS = [
    INPUT_DIR,
    OUTPUT_LONG_DIR,
    OUTPUT_SHORTS_DIR,
    OUTPUT_VERTICAL_DIR,
    OUTPUT_SUBTITLES_DIR,
    OUTPUT_THUMBNAILS_DIR,
    CACHE_AUDIO_DIR,
    CACHE_AUDIO_CHUNKS_DIR,
    CACHE_METADATA_DIR,
    CACHE_TRANSCRIPTS_DIR,
    CACHE_TRANSCRIPTION_CHUNKS_DIR,
    CACHE_HIGHLIGHTS_DIR,
    CACHE_EDIT_PLANS_DIR,
    CACHE_EMOTIONS_DIR,
    CACHE_TITLES_DIR,
    CACHE_PUBLISH_DIR,
    CACHE_LEARNING_DIR,
    CACHE_ANALYTICS_DIR,
    DATA_ANALYTICS_DIR,
    ASSETS_SFX_DIR,
    ASSETS_FONTS_DIR,
    ASSETS_OVERLAYS_DIR,
    CACHE_VIDEO_DIR,
    CACHE_CONTEXT_DIR,
]


def ensure_project_dirs() -> None:
    for directory in PROJECT_DIRS:
        directory.mkdir(parents=True, exist_ok=True)
